version: '3.8'

services:
  bot:
    build: .
    container_name: worldcup_bot
    restart: always
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - REDIS_HOST=redis
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    container_name: worldcup_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    container_name: worldcup_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
